# Project
group=dev.ultreon.quants

# Java
java_version=21

# Common
quantum_version=0.2.0-SNAPSHOT
fabric_loader_version=0.16.14

# Mod options
mod_version=1.12.1
mod_name=Quantalogue
mod_author=MrCrayfish
mod_id=Quantalogue
mod_desc=A modern mod list menu designed for all modloaders
mod_homepage=https://mrcrayfish.com/mods?id=Quantalogue
mod_source=https://github.com/MrCrayfish/Quantalogue
mod_issues=https://github.com/MrCrayfish/Quantalogue/issues
mod_license=MIT

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false